services:
  - type: web
    name: dayflow-api
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_APP_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: FRONTEND_URL
        fromService:
          type: web
          name: dayflow-hrms
          property: host

  - type: web
    name: dayflow-hrms
    runtime: static
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: dayflow-api
          property: host
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
